apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring-app
          image: gegurakzi/spring-app:latest
          ports:
            - name: httpport
              containerPort: 8080