apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: deployments
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /
    prometheus.io/port:   '8080'
spec:
  selector:
    app: spring-server
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000